remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Maeve's Data Science Site]
description: [A place to keep track of helpful information and links.]
